@base = {{$dotenv BASE_URL}}

### Registro de usuario
POST {{base}}/api/auth/register
Content-Type: application/json

{
  "nombre": "Admin",
  "email": "admin@mail.com",
  "password": "admin123"
}

### Login de usuario
POST {{base}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin123"
}

